insert into clientes(nombre,apellido,email,create_at) values ("Silvana","Munoz","silvi@gmail.com","2022-01-01");
insert into clientes(nombre,apellido,email,create_at) values ("Silvana","Munoz","silvas@gmail.com","2022-01-01");
insert into clientes(nombre,apellido,email,create_at) values ("Silvana","Munoz","silvana@gmail.com","2022-01-01");
insert into clientes(nombre,apellido,email,create_at) values ("Silvana","Munoz","silstefi@gmail.com","2022-01-01");
insert into clientes(nombre,apellido,email,create_at) values ("Silvana","Munoz","silmu@gmail.com","2022-01-01");
insert into clientes(nombre,apellido,email,create_at) values ("Silvana","Munoz","silva@gmail.com","2022-01-01");
insert into clientes(nombre,apellido,email,create_at) values ("Silvana","Munoz","silvamu@gmail.com","2022-01-01");
insert into clientes(nombre,apellido,email,create_at) values ("Silvana","Munoz","silmuva@gmail.com","2022-01-01");
insert into clientes(nombre,apellido,email,create_at) values ("Silvana","Munoz","sil@gmail.com","2022-01-01");
